transcend-io/penumbra

- example/package-lock.json
- example/package.json
- package-lock.json
- package.json
`npm run check:deps:interactive`
> Updates dependencies and adds scripts to interactively update

- .airtap.yml
- package-lock.json
- package.json
- src/tests/downloadEncryptedFile.test.ts
- src/tests/fetchAndDecrypt.test.ts
- src/tests/getDecryptedContent.test.ts
- src/tests/helpers/index.ts
- src/tests/helpers/timeout.ts
Adding tests for downloadEncryptedFile which will help me test solutions for #17.
> Add downloadEncryptedFile  tests

- src/API.ts
- src/decrypt.penumbra.worker.js
- src/demo/demo.js
- src/types.ts
- src/workers.ts
> WritableStreams fallback for Firefox and Safari compatibility

- README.md
- example/index.js
- package-lock.json
- package.json
- src/API.ts
- src/demo/demo.js
- src/tests/v3-api.test.ts
- src/types.ts
This set of commits improves the getTextOrURI() for batch use.
> Improve getTextOrURI API

- package.json
- src/fetchAndDecrypt.ts
> Emit error

- babel.config.js
- package.json
- webpack.config.js
> Restore some old build settings

- package.json
Types were removed in recent webpack refactor
> Adds declaration map in build

- example/displayTable.js
- example/files.js
- example/index.html
- example/index.js
- example/jsAnimation.js
- example/style.css
- example/web-crypto.html
- example/web-crypto.js
- package.json
- webpack.dev.js
- webpack.prod.js
- yarn.lock
Adds a comparison vs. Web Crypto.
Adds an animation to show any differences in browser responsiveness/UI jank.
Resolves: https://github.com/transcend-io/penumbra/issues/125
> Add web crypto demo

- README.md
- package.json
- src/API.ts
- src/events.d.ts
- src/penumbra.worker.js
- src/transferHandlers/penumbra-events.ts
- src/types.ts
- src/utils/emitEncryptionCompletion.ts
- src/utils/forwardEvents.ts
This PR corrects some incorrect inline documentation
> Inline docs fixes

- package.json
- src/@types/promise.allsettled/index.d.ts
- src/zip.ts
- yarn.lock
This PR adds a shim for browsers that don't yet support `Promise.allSettled`.
> Use Promise.allSettled shim/polyfill

- package.json
- src/API.ts
Fixing some code that could potentially be causing issues in Safari
> This could potentially be causing issues in Safari

- .github/workflows/ci.yml
- package.json
think i forgot this in last pr
> Bumps penumbra version

- .github/workflows/ci.yml
- https://github.com/transcend-io/penumbra/issues/209
Flakey browserstack
> Publish to npm without karama tests passing

- package.json
- yarn.lock
Updating to pull in dependabot free conflux
> Updates conflux version

- README.md
> Remove reference to Netlify and add Vercel

- package.json
- src/utils/isNumber.ts
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/isnan#confusing_special-case_behavior
- _[none]_
_[none]_
_[none]_
> Use `Number.isNaN()` over `isNaN()`.

- karma.local.js
- package.json
Just something I discovered while hacking away at Penumbra -- makes debugging soooo much easier.
- _[none]_
_[none]_
_[none]_
> Allow local Karma, non-browser based debugging.

- yarn.lock
Closes https://github.com/transcend-io/penumbra/security/dependabot/103
> Update ws/braces package versions

- package.json
- yarn.lock
> Bump elliptic/cookie/body-parser deps to avoid vulns

- .github/workflows/ci.yml
- .prettierignore
- README.md
- example/index.html
- example/web-crypto.html
- penumbra-karma-context.html
- src/worker.penumbra.js
- tests/api.test.ts
Updates:
- CI workflow to skip flaky karma/browserstack
- additions from pre-commit
- ignoring import statement breaking prettier in example file
> Fix publish CI

- .github/workflows/ci.yml
Fixes:
- github action file referencing job that no longer exists
> fix actions file
